sdran:
  platform:
    atomix:
      helm:
        chart_ref: atomix/atomix
        chart_version: 1.1.2

    onosproject:
      helm:
        chart_ref: onosproject/onos-operator
        chart_version: 0.5.6

    store:
      lpp:
        version: v0.0.24

  sdran:
    helm:
      chart_ref: "sdran/sd-ran"
      chart_version: 1.4.135
    import:
      e2t: true
      a1t: true
      uenib: true
      topo: true
      config: true
      ransim: true
      kpimon: true
      pci: false # true for PCI and MLB use-case
      mho: false # true for MHO use-case
      mlb: false # true for MLB use-case
      ts: false # true for traffic steering use-case
    ransim:
      model: model # default: model; mlb: three-cell-n-node-model; mho: two-cell-two-node-model; ts: two-cell-two-node-model
      metric: metrics # default: model; mlb: three-cell-n-node-model
