---
- name: Clone UERANSIM repository
  git:
    repo: https://github.com/aligungr/UERANSIM.git
    dest: UERANSIM
  tags:
    - install

- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - g++
    - pkg-config
    - libsctp-dev
    - iproute2
    - make
  tags:
    - install

- name: Install cmake
  snap:
    name: cmake
    state: present
    classic: true
  tags:
    - install

- name: Build UERANSIM
  shell: cmake . && make
  args:
    chdir: UERANSIM
  tags:
    - install

- name: configure static route for upf traffic on ueransim node
  shell: |
    ip route add {{ core.upf.ip_prefix }} via {{ core.amf.ip }}
